# Basic configuration for PaperCraft

[output]
format = "pdf"
quality = 1.0
compression = true

[page]
orientation = "portrait"

[page.size]
preset = "A4"

[page.margins]
top = "1in"
right = "1in"
bottom = "1in"
left = "1in"

[page.page_numbers]
enabled = true
format = "Page {page} of {total}"
position = "footer"
start_from = 1

[theme]
built_in = "default"

[fonts]
family = "Arial, sans-serif"
size = "12pt"
line_height = 1.6